apiVersion: apps/v1
kind: Deployment
metadata:
  name: miiify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miiify
  template:
    metadata:
      labels:
        app: miiify
    spec:
#      nodeSelector:
#        disktype: ssd
      containers:
        - name: miiify
          image: jptmoore/miiify
          args: ["--config=/etc/config/config.json"]
          ports:
            - containerPort: 8080
              name: miiify
          volumeMounts:
            - name: miiify
              mountPath: /data
            - name: miiify-config
              mountPath: /etc/config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: miiify
          persistentVolumeClaim:
            claimName: "miiify-pvc"
        - name: miiify-config
          configMap:
            name: miiify
